version: "3.7"

services:
  node-dev-env:
    build: .
    command: npm start -L
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: node-dev-env

volumes:
  node_modules:
