version: "3.8"

services:
  redis-service:
    image: redis

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile.back
      args:
        - PORT=8080
        - REDIS_HOST=redis-service
        - REQUEST_ORIGIN=*
    ports:
      - 8080:8080
    depends_on:
      - redis-service

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile.front
      args:
        - PORT=5000
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
    depends_on:
      - redis-service
