FROM ubuntu:latest

WORKDIR /usr/src/app

RUN apt-get update 

RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash

RUN apt-get install -y nodejs

RUN node -v && npm -v

COPY ./example-frontend/ .

RUN npm install

ENV PORT=5000
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm run build

RUN npm install -g serve

EXPOSE ${PORT}

CMD serve -s -l ${PORT}  build