version: "3.8"

services:
  redis-service:
    image: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres-service:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile.back
      args:
        - PORT=8080
        - REDIS_HOST=redis-service
        - POSTGRES_HOST=postgres-service
        - POSTGRES_PASSWORD=example
        - REQUEST_ORIGIN=*
    ports:
      - 8080:8080
    depends_on:
      - postgres-service
      - redis-service

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile.front
      args:
        - PORT=5000
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
    depends_on:
      - postgres-service
      - redis-service

volumes:
  postgres_data:
  redis_data:
