version: "3.8"

services:
  training:
    build:
      context: ./ml-kurkkumopo-training-master
    volumes:
      - images:/src/imgs
      - model:/src/model

  backend:
    build:
      context: ./ml-kurkkumopo-backend-master
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - training

  frontend:
    build:
      context: ./ml-kurkkumopo-frontend-master
    ports:
      - 3000:3000
    depends_on:
      - backend
      - training

volumes:
  model:
  images:
